#!/bin/sh

inotifywait -m ~/Desktop/image -e create -e moved_to |
    while read path action file; do
        echo "The file '$file' appeared in directory '$path' via '$action'"
        result=$(python3 /home/pi/Documents/GitHub/M.E.P./src/Server/Python_VisionRequest/VisionRequest.py $path/$file)
        echo $result
        cd /home/pi/Documents/GitHub/M.E.P./src/Connection/string
        if [ -e string.txt ]; then
            #echo "file string.txt already exists"
            rm string.txt
        fi
        echo $result > string.txt
        cd ~/processing-3.3.6
        ./processing-java --sketch=/home/pi/Documents/GitHub/M.E.P./src/Connection/string --run
    done
